---
- hosts: all 
  remote_user: pi
  tasks:
    - name: shutdown machine
      shell: sleep 2 && shutdown -h now "Ansible updates triggered"
      async: 1 
      poll: 0
      sudo: true
      ignore_errors: true

